services:
  mysql:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Rezadmin@1234
      MYSQL_DATABASE: jwt_security
      MYSQL_USER: root
      MYSQL_PASSWORD: Rezadmin@1234
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: Rezadmin@1234
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
